/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ahmad.calculator;

import org.junit.jupiter.api.Test;

import ahmad.Calculator;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    @DisplayName("Adding Test")
    void appMustAdding () {
        assertEquals(9, Calculator.adding(4, 5));
    }
}
