/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ahmad.calculator;

import ahmad.Calculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Calculator().adding(4, 5));
    }
}
